// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'user_list_block': string;
  'user_list_found': string;
}
export const cssExports: CssExports;
export default cssExports;
