// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'sort_list_block': string;
  'sort_list_label': string;
  'sort_list_select': string;
  'sort_list_select_wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
