// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'error_field': string;
  'user_form': string;
  'user_form_fields': string;
  'user_form_tooltip': string;
}
export const cssExports: CssExports;
export default cssExports;
