// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'user_item_block': string;
  'user_item_field_name': string;
  'user_item_field_value': string;
  'user_item_main_info': string;
  'user_item_more_info': string;
}
export const cssExports: CssExports;
export default cssExports;
